openapi: 3.1.1
info:
  title: Booking Service API
  summary: Booking microservice API
  description: >
    This service manages bookings made by users for scheduled movies.
    Access is controlled using the `X-User-Id` header:
      - Administrators or owners can manage user bookings.
      - Administrators can retrieve the list of users who booked a specific movie.
  contact:
    name: Noé Jouan - Evan Runemberg
    url: https://imt-atlantique.fr/
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

tags:
  - name: public
    description: Endpoints that do not require authentication
  - name: secured
    description: Endpoints requiring the `X-User-Id` header (admin or owner)
  - name: admin
    description: Endpoints restricted to administrators only

paths:
  /:
    get:
      tags:
        - public
      summary: Service home page
      description: Returns a simple HTML welcome message.
      operationId: home
      responses:
        "200":
          description: Welcome message
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the Booking service!</h1>"

  /bookings/{userid}:
    get:
      tags:
        - secured
      summary: Get all bookings for a user
      description: >
        Returns all bookings for a given user.
        Accessible to the owner or an administrator.
      operationId: get_bookings_for_user
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        "200":
          description: Bookings found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserBookings"
        "404":
          description: No bookings found for this user
        "401":
          description: Missing header
        "403":
          description: Forbidden (not admin nor owner)

    post:
      tags:
        - secured
      summary: Add a booking for a user
      description: >
        Adds a booking (movie + date) for the specified user.
        Accessible to the owner or an administrator.

        This endpoint:
          - Verifies the date exists using the Schedule Service  
          - Checks the movie is scheduled on that date  
          - Prevents duplicated bookings
      operationId: add_booking
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Booking details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingInput"
      responses:
        "200":
          description: Booking added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: booking added
        "400":
          description: Missing fields or movie not scheduled on this date
        "404":
          description: Date not found in schedule
        "409":
          description: Booking already exists
        "503":
          description: Schedule service unavailable
        "401":
          description: Missing header
        "403":
          description: Forbidden

    delete:
      tags:
        - secured
      summary: Delete a booking for a user
      description: >
        Deletes a booking (movie + date) for the specified user.
        Accessible to the owner or an administrator.
      operationId: delete_booking
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
            description: User identifier
      requestBody:
        required: true
        description: Booking to remove
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingInput"
      responses:
        "200":
          description: Booking deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: booking deleted
        "400":
          description: Missing fields
        "404":
          description: Booking not found
        "401":
          description: Missing header
        "403":
          description: Forbidden

  /bookings/movie/{movie_id}:
    get:
      tags:
        - admin
      summary: List users who booked a specific movie
      description: >
        Returns the list of users who booked a given movie, with associated dates.
        Accessible **only to administrators**.

        This endpoint:
          - Validates the movie exists using the Movie Service
      operationId: get_users_for_movie
      security:
        - UserHeaderAuth: []
      parameters:
        - name: movie_id
          in: path
          required: true
          schema:
            type: string
          description: Movie identifier
      responses:
        "200":
          description: Users who booked this movie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieBookings"
        "404":
          description: Movie not found or no bookings found
        "503":
          description: Movie service unavailable
        "401":
          description: Missing header
        "403":
          description: Forbidden (admin only)

components:
  securitySchemes:
    UserHeaderAuth:
      type: apiKey
      in: header
      name: X-User-Id
      description: >
        ID of the calling user, used to verify:
        - whether the user is an administrator
        - whether the user is the resource owner

  schemas:
    BookingInput:
      type: object
      required:
        - date
        - movie
      properties:
        date:
          type: string
          example: "20250412"
        movie:
          type: string
          example: "a8034f44-aee4-44cf-b32c-74cf452aaaae"

    UserBookings:
      type: object
      properties:
        userid:
          type: string
          example: "alice01"
        dates:
          type: array
          items:
            $ref: "#/components/schemas/BookingDate"

    BookingDate:
      type: object
      properties:
        date:
          type: string
          example: "20250412"
        movies:
          type: array
          items:
            type: string
            example: "a8034f44-aee4-44cf-b32c-74cf452aaaae"

    MovieBookings:
      type: object
      properties:
        movie:
          type: object
          description: Movie details returned by the Movie Service
        users:
          type: array
          items:
            type: object
            properties:
              userid:
                type: string
                example: "alice01"
              date:
                type: string
                example: "20250412"
