openapi: 3.1.1

info:
  title: Schedule Service API
  summary: Showtime schedule microservice API
  description: >
    This service manages movie schedules for specific dates.

    Access control uses the **X-User-Id** header:

    - Only **administrators** can create or delete schedules.
    - Public endpoints do not require authentication.

  contact:
    name: Noé Jouan - Evan Runemberg
    url: https://imt-atlantique.fr/

  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

  version: 1.0.0

tags:
  - name: public
    description: Endpoints that do not require authentication
  - name: admin
    description: Endpoints restricted to administrators only

paths:

  /:
    get:
      tags:
        - public
      summary: Service home page
      description: Returns a simple HTML welcome message.
      operationId: home
      responses:
        "200":
          description: Welcome message
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the Showtime service!</h1>"

  /schedules/{date}:
    get:
      tags:
        - public
      summary: Get schedule by date
      description: >
        Returns the schedule (date + movie IDs) for a given day.
      operationId: get_schedule_bydate
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Schedule found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        "404":
          description: No schedule exists for the selected date
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      tags:
        - admin
      summary: Delete a schedule
      description: >
        Deletes the schedule for the given date.  
        **Admin only** (via X-User-Id header).
      operationId: del_schedule
      security:
        - UserHeaderAuth: []
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Schedule deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        "404":
          description: Schedule not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing header
        "403":
          description: Forbidden (not admin)

  /schedules/{date}/movies:
    get:
      tags:
        - public
      summary: Get full schedule with movie details
      description: >
        Fetches movie IDs from the schedule **and retrieves full movie details**  
        from the Movies microservice.
      operationId: get_schedule_details
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Schedule with detailed movie information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleWithMovies"
        "404":
          description: No schedule or no movies found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /schedules:
    post:
      tags:
        - admin
      summary: Add a new schedule
      description: >
        Creates a schedule for a given date.  
        **Admin only** (X-User-Id must be an administrator).
      operationId: add_schedule
      security:
        - UserHeaderAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Schedule"
      responses:
        "200":
          description: Schedule successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "409":
          description: Schedule date already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing header
        "403":
          description: Forbidden (not admin)

components:

  securitySchemes:
    UserHeaderAuth:
      type: apiKey
      in: header
      name: X-User-Id
      description: >
        ID of the calling user, used to verify administrator permissions.

  schemas:

    Schedule:
      type: object
      required:
        - date
        - movies
      properties:
        date:
          type: string
          format: date
          example: "20250320"
        movies:
          type: array
          description: List of movie IDs
          items:
            type: string
            example: "a8034f44-aee4-44cf-b32c-74cf452aaaae"

    Movie:
      type: object
      description: Movie details returned by the Movies Service
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        year:
          type: integer
      example:
        id: "a8034f44-aee4-44cf-b32c-74cf452aaaae"
        title: "Inception"
        director: "Christopher Nolan"
        year: 2010

    ScheduleWithMovies:
      type: object
      required:
        - date
        - movies
      properties:
        date:
          type: string
          format: date
        movies:
          type: array
          items:
            $ref: "#/components/schemas/Movie"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      example:
        error: "No schedule for this date"

    MessageResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: "schedule added"
