openapi: 3.1.1
info:
  title: User Service API
  summary: User microservice API
  description: >
    This service manages users (CRUD).
    Access is controlled using the `X-User-Id` header:
      - Only administrators can add users.
      - Administrators or owners can read, update, and delete.
  contact:
    name: Noé Jouan - Evan Runemberg
    url: https://imt-atlantique.fr/
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

tags:
  - name: public
    description: Endpoints that do not require authentication
  - name: secured
    description: Endpoints requiring the `X-User-Id` header (admin or owner)
  - name: admin
    description: Endpoints restricted to administrators only

paths:
  /:
    get:
      tags:
        - public
      summary: Service home page
      description: Returns a simple HTML welcome message.
      operationId: home
      responses:
        "200":
          description: Welcome message
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the User service!</h1>"

  /users:
    post:
      tags:
        - admin
      summary: Add a new user
      description: >
        Creates a new user.
        Accessible **only to administrators** (`X-User-Id` must belong to an admin).
      operationId: add_user
      security:
        - UserHeaderAuth: []
      requestBody:
        required: true
        description: User data to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserItem"
      responses:
        "200":
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: user added
        "409":
          description: User ID already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User ID already exists
        "401":
          description: Missing header
        "403":
          description: Forbidden (not an admin)

  /users/{userid}:
    get:
      tags:
        - secured
      summary: Get a user by ID
      description: >
        Returns user information.
        Accessible to the owner or an admin.
      operationId: get_user_byid
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
          description: User identifier
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserItem"
        "404":
          description: User not found
        "401":
          description: Missing header
        "403":
          description: Forbidden (not admin nor owner)

    put:
      tags:
        - secured
      summary: Update a user
      description: >
        Updates an existing user.
        Accessible to the owner or an admin.
      operationId: update_user
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserItem"
      responses:
        "200":
          description: User updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserItem"
        "404":
          description: User not found
        "401":
          description: Missing header
        "403":
          description: Forbidden

    delete:
      tags:
        - secured
      summary: Delete a user
      description: >
        Deletes a user.
        Accessible to the owner or an admin.
      operationId: del_user
      security:
        - UserHeaderAuth: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserItem"
        "404":
          description: User not found
        "401":
          description: Missing header
        "403":
          description: Forbidden

components:
  securitySchemes:
    UserHeaderAuth:
      type: apiKey
      in: header
      name: X-User-Id
      description: >
        ID of the calling user, used to verify:
        - whether the user is an administrator
        - whether the user is the resource owner

  schemas:
    UserItem:
      type: object
      required:
        - id
        - name
        - is_admin
      properties:
        id:
          type: string
          example: alice01
        name:
          type: string
          example: Alice Martin
        is_admin:
          type: boolean
          example: false
